
services:
  rabbit:
    image: rabbitmq:4.0-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak
    ports:
      - "7080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "tharphyo/configserver:v1"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: [ "CMD-SHELL", "echo 'Checking connection' && timeout 1 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/8071'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config
    environment:
      OTEL_SERVICE_NAME: "configserver"

  eurekaserver:
    image: "tharphyo/eurekaserver:v1"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "echo 'Checking connection' && timeout 1 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/8070'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      OTEL_SERVICE_NAME: "eurekaserver"

  accounts:
    image: "tharphyo/accounts:v1"
    container_name: accounts-ms
    healthcheck:
      test: [ "CMD-SHELL", "echo 'Checking connection' && timeout 1 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/8080'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      OTEL_SERVICE_NAME: "accounts"
      SPRING_RABBITMQ_HOST: "rabbit"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "tharphyo/loans:v1"
    container_name: loans-ms
    healthcheck:
      test: [ "CMD-SHELL", "echo 'Checking connection' && timeout 1 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/8090'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      OTEL_SERVICE_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  #loans1:
  # image: "tharphyo/loans:v1"
  # container_name: loans-ms1
  # ports:
  #   - "8091:8090"
  # healthcheck:
  #   test: [ "CMD-SHELL", "echo 'Checking connection' && timeout 1 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/8091'" ]
  #   interval: 10s
  #   timeout: 5s
  #   retries: 10
  #   start_period: 10s
  # depends_on:
  #   configserver:
  #     condition: service_healthy
  #   eurekaserver:
  #     condition: service_healthy
  # environment:
  #   SPRING_APPLICATION_NAME: "loans"
  # extends:
  #   file: common-config.yml
  #   service: microservice-eureka-config

  cards:
    image: "tharphyo/cards:v1"
    container_name: cards-ms
    healthcheck:
      test: [ "CMD-SHELL", "echo 'Checking connection' && timeout 1 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/9000'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      OTEL_SERVICE_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  message:
    image: "tharphyo/message:v1"
    container_name: message-ms
    depends_on:
      rabbit:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
    extends:
      file: common-config.yml
      service: network-deploy-service

  gatewayserver:
    image: "tharphyo/gatewayserver:v1"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      OTEL_SERVICE_NAME: "gatewayserver"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  phyobank:
    driver: bridge
